import type { Metadata } from "next";
import { inter } from './fonts'
import "./globals.css";

export const metadata: Metadata = {
  title: "FTOYD test",
  description: "Generated by create next app",
};

import { Providers } from './providers'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
